# Generated by Django 5.2.1 on 2025-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_handwritingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritingresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
