# Generated by Django 5.1.7 on 2025-05-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0004_certificateapplication_secondprogramapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateapplication',
            old_name='class_name',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='secondprogramapplication',
            old_name='class_name',
            new_name='student_class',
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='secondprogramapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
